### User Services - Login (Token)
POST http://localhost:8000/api/v1/user-service/auth/login
Content-Type: application/json

{
  "userId": "testuser01",
  "password": "password#"
}


> {%
    client.global.set("auth_token", response.body.data.accessToken);
    client.log("Auth Token: " + client.global.get("auth_token"));
%}

### Notification Service

### 1. 알람 읽음 처리
GET http://localhost:8000/api/v1/ingredient-stock-service/notification/83
Authorization: Bearer {{auth_token}}

### 2. 알림 일괄 생성
POST http://localhost:8000/api/v1/ingredient-stock-service/notifications
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[
  {
    "userNo": 1,
    "notificationTypeNo": 1,
    "notificationContent": "테스트 알림입니다."
  }
]

### 3. 내 알림 목록 조회
GET http://localhost:8000/api/v1/ingredient-stock-service/api/v1/notification
Authorization: Bearer {{auth_token}}
