### 회원가입
POST http://localhost:8000/api/v1/user-service/users
Content-Type: application/json

{
  "userId": "testuser01",
  "password": "testuserpwd@",
  "nickname": "sinwooTest",
  "email": "testuser01@gmail.xom",
  "phoneNum": "01012345678",
  "birthdate": "2025-06-06"
}

### 로그인
POST http://localhost:8000/api/v1/user-service/auth/login
Content-Type: application/json

{
  "userId": "testuser01",
  "password": "password#"
}

> {%
    // 응답 결과에서 accessToken 값을 추출하여 auth_token 변수에 저장
    client.global.set("auth_token", response.body.data.accessToken);
    client.global.set("refresh_token", response.body.data.refreshToken);
%}

### 조회 {user_id}
GET http://localhost:8000/api/v1/user-service/users/testuser01
Accept: application/json
Authorization: Bearer {{auth_token}}

### 조회 {user_no}
GET http://localhost:8000/api/v1/user-service/users/by-no/2
Accept: application/json
Authorization: Bearer {{auth_token}}

### 내정보(로그인유저) 조회
GET http://localhost:8000/api/v1/user-service/users/myinfo
Accept: application/json
Authorization: Bearer {{auth_token}}

### 회원정보 수정 (email, phoneNum)
PATCH http://localhost:8000/api/v1/user-service/users
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "rlatlsdn98@gmail.com",
  "phoneNum": "010-9999-1192"
}

### 회원정보 수정 (password)
PATCH http://localhost:8000/api/v1/user-service/users/password
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "resentPassword": "testuserpwd@",
  "newPassword": "password#",
  "checkNewPassword": "password#"
}

### 로그아웃
POST http://localhost:8000/api/v1/user-service/auth/logout
Authorization: Bearer {{auth_token}}

### 회원탈퇴
DELETE http://localhost:8000/api/v1/user-service/users
Accept: application/json
Authorization: Bearer {{auth_token}}